from __future__ import annotations

from pathlib import Path

from ..models import DrumPattern


SOUNDS = {
    "kick": "bd",
    "snare": "sd",
    "closed_hat": "hh",
    "open_hat": "oh",
    "percussion": "rim",
}


def _bar_tokens(pattern: DrumPattern, instrument: str, bar: int) -> str:
    by_step = {
        hit.step: hit
        for hit in pattern.hits.get(instrument, [])
        if hit.bar == bar
    }
    return " ".join(SOUNDS[instrument] if step in by_step else "~" for step in range(pattern.steps_per_bar))


def _pattern_string(pattern: DrumPattern, instrument: str) -> str:
    bars = [_bar_tokens(pattern, instrument, bar) for bar in range(pattern.bars)]
    return " | ".join(bars)


def write_strudel(pattern: DrumPattern, output_path: Path) -> None:
    layers: list[str] = []
    gains = {
        "kick": "1",
        "snare": "0.95",
        "closed_hat": "0.38",
        "open_hat": "0.28",
        "percussion": "0.22",
    }

    for instrument in SOUNDS:
        if not pattern.hits.get(instrument):
            continue
        mini = _pattern_string(pattern, instrument)
        chain = f'  s("{mini}").gain({gains[instrument]})'
        if instrument in {"closed_hat", "open_hat", "percussion"}:
            chain += '.pan("<0.35 0.65>")'
        layers.append(chain)

    body = ",\n".join(layers)
    source_name = Path(pattern.source_audio).name
    controls = pattern.metadata.get("controls", {})
    swing = controls.get("swing", 0.0)
    humanize = controls.get("humanize", 0.0)
    code = f"""// Generated by Breaksmith from {source_name}
// Style: {pattern.name} | BPM: {pattern.bpm:.2f} | Bars: {pattern.bars}
// Timing: MIDI/JSON include swing and humanization offsets; Strudel keeps the editable grid.
// Controls: density={controls.get("density", "n/a")} swing={swing} humanize={humanize} variation={controls.get("variation", "n/a")}

setcpm({pattern.bpm:.6g} / 4)

stack(
{body}
)
"""
    output_path.write_text(code, encoding="utf-8")
